title: LTSEC Docs
description: Documentation and other written tomfoolery from LTSEC!
theme: just-the-docs

url: https://ltsec.github.io
logo: "/assets/images/LTSEC_Docs_Dark.png"

color_scheme: ltsec

footer_content: "Copyright &copy; 2022 LTSEC. Distributed by an <a href=\"https://github.com/LTSEC/ltsec.github.io/blob/main/LICENSE\">MIT license.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
